endpoint: wss://asset-hub-paseo-rpc.dwellir.com
mock-signature-host: true
block: ${env.PASEO_ASSET_HUB_BLOCK_NUMBER}
db: ./asset-hub-db.sqlite
runtime-log-level: 5
wasm-override: ../runtimes/asset-hub-paseo-runtime-1006000.wasm
